# Generated by Django 6.0.1 on 2026-01-15 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='book',
            field=models.ForeignKey(db_column='book_isbn', on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='book.book'),
        ),
    ]
