# Generated by Django 6.0.1 on 2026-01-20 22:59

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_author_bio_alter_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.utils.UploadTo('author/')),
        ),
    ]
