# Generated by Django 6.0.1 on 2026-01-22 11:02

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_cover_image_bookimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to=apps.core.utils.UploadTo('book/')),
        ),
    ]
