# Generated by Django 6.0.1 on 2026-01-22 21:15

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_email_alter_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=14, region=None),
        ),
    ]
