# Generated by Django 6.0.1 on 2026-01-09 12:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0003_alter_bookcopy_options_alter_author_death_date'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CirculationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrow_date', models.DateTimeField(default=datetime.datetime(2026, 1, 9, 12, 29, 8, 142050, tzinfo=datetime.timezone.utc))),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue')], max_length=20)),
                ('fine', models.IntegerField(blank=True, default=0)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookcopy')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
