# Generated by Django 6.0.1 on 2026-01-22 21:28

import apps.circulation.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulationrecord',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='circulationrecord',
            name='borrow_date',
            field=models.DateTimeField(default=datetime.datetime.today, validators=[apps.circulation.models.validate_borrow_date]),
        ),
    ]
