# Generated by Django 6.0.1 on 2026-01-22 21:37

import apps.circulation.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0002_circulationrecord_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulationrecord',
            name='borrow_date',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[apps.circulation.models.validate_borrow_date]),
        ),
    ]
