# Generated by Django 6.0.1 on 2026-01-22 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_cover_image'),
        ('circulation', '0003_alter_circulationrecord_borrow_date'),
        ('member', '0003_alter_member_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulationrecord',
            name='book_copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circulations', to='book.bookcopy'),
        ),
        migrations.AlterField(
            model_name='circulationrecord',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='member.member'),
        ),
    ]
