# Generated by Django 6.0.1 on 2026-01-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0004_alter_circulationrecord_book_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulationrecord',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='active', max_length=20),
        ),
    ]
