# Generated by Django 6.0.1 on 2026-01-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0005_alter_circulationrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulationrecord',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('returned', 'Returned')], default='active', max_length=20),
        ),
    ]
